"""Per-finding AI validator for rule-engine output."""

from __future__ import annotations

import asyncio
from typing import Any, Dict, List, Tuple

VALIDATOR_SYSTEM_PROMPT = """You are a DPDP Act 2023 compliance validator.
You will receive:
1. A compliance finding generated by a rule engine
2. The FULL content of the file the finding is about
3. AI-generated context explaining what the file actually does

Your job: determine if the finding is a TRUE POSITIVE or FALSE POSITIVE.

A finding is a FALSE POSITIVE if:
- The rule fired on a file that is clearly not responsible for the violation
- The pattern matched a false positive (e.g. PASSWORD_NOT_HASHED on a DB adapter)
- The file's actual purpose makes the finding inapplicable

A finding is a TRUE POSITIVE if:
- The file actually performs the action the rule describes
- The violation genuinely exists in this specific file

A finding should be DOWNGRADED if:
- The violation exists but is minor or has mitigating factors

RESPONSE FORMAT — JSON ONLY:
{
  "verdict": "confirmed|rejected|downgraded",
  "confidence": 0.0-1.0,
  "reasoning": "specific explanation citing actual code in the file",
  "downgrade_to": "MEDIUM|LOW|INFO (only if verdict is downgraded)",
  "better_file": "if this finding belongs on a different file, name it here",
  "specific_line": "the exact line of code that is the actual violation, or null"
}"""


def _build_validation_prompt(
    finding: Dict,
    file_content: str,
    file_context: Dict,
    repo_memory: Dict,
) -> str:
    rule = finding.get("rule", "")
    severity = finding.get("severity", "")
    dpdp_section = finding.get("dpdp_section", "")
    description = finding.get("description", "")
    file_path = finding.get("file", "")

    related_contexts = []
    evidence = finding.get("evidence") or {}
    for key in ("pii_fields", "libraries"):
        for item in (evidence.get(key) or [])[:3]:
            if isinstance(item, dict):
                related_file = item.get("file", "")
                if related_file and related_file != file_path:
                    ctx = repo_memory.get(related_file)
                    if ctx:
                        related_contexts.append(
                            f"Related file {related_file}: "
                            f"{ctx.get('primary_purpose', 'unknown')}"
                        )

    related_str = (
        "\n".join(related_contexts)
        if related_contexts
        else "No related file context available"
    )

    context_summary = ""
    if file_context and file_context.get("file_type") != "unknown":
        context_summary = f"""
AI File Context:
- File type: {file_context.get('file_type')}
- Purpose: {file_context.get('primary_purpose')}
- Collects PII from users: {file_context.get('collects_pii_from_users')}
- PII collected: {file_context.get('pii_collected')}
- Is user-facing: {file_context.get('is_user_facing')}
- Is internal only: {file_context.get('is_internal_only')}
- Has auth check: {file_context.get('has_auth_check')}
- Framework patterns: {file_context.get('framework_patterns')}
- Why not a violation (if applicable): {file_context.get('why_not_a_violation')}
"""

    return f"""Validate this DPDP compliance finding:

FINDING:
Rule: {rule}
Severity: {severity}
Section: {dpdp_section}
File: {file_path}
Description: {description}

{context_summary}

Related files context:
{related_str}

FULL FILE CONTENT ({file_path}):
{file_content}

Is this finding a true positive or false positive?
Cite specific lines from the file in your reasoning."""


async def validate_finding_async(
    finding: Dict,
    file_content: str,
    file_context: Dict,
    repo_memory: Dict,
    llm_client: Any,
) -> Tuple[Dict, Dict]:
    file_path = finding.get("file", "")
    if not file_path or file_path in ("N/A", "REPO-WIDE", ""):
        return finding, {
            "verdict": "confirmed",
            "confidence": 0.50,
            "reasoning": "No specific file to validate against",
        }

    prompt = _build_validation_prompt(
        finding, file_content, file_context, repo_memory
    )

    loop = asyncio.get_event_loop()

    def _call():
        return llm_client.complete_json(
            system_prompt=VALIDATOR_SYSTEM_PROMPT,
            user_prompt=prompt,
            quality=False,
            layer="layer2",
        )

    result = await loop.run_in_executor(None, _call)

    if not isinstance(result, dict):
        return finding, {
            "verdict": "confirmed",
            "confidence": 0.50,
            "reasoning": "Validation parse failed — defaulting to confirmed",
        }

    return finding, result


def validate_all_findings(
    findings: List[Dict],
    file_contents: Dict[str, str],
    repo_memory: Dict,
    llm_client: Any,
) -> Tuple[List[Dict], List[Dict]]:
    from rich.console import Console

    console = Console()
    console.print(f"\n  [bold]Validating {len(findings)} finding(s)...[/bold]")

    findings_to_validate = [
        f
        for f in findings
        if f.get("severity") in ("HIGH", "MEDIUM")
        and f.get("file") not in ("N/A", "REPO-WIDE", "", None)
    ]
    skip_validation = [f for f in findings if f not in findings_to_validate]

    async def run_all_validations():
        tasks = []
        for finding in findings_to_validate:
            file_path = finding.get("file", "")
            file_content = file_contents.get(file_path, "")
            file_context = repo_memory.get(file_path, {})
            tasks.append(
                validate_finding_async(
                    finding,
                    file_content,
                    file_context,
                    repo_memory,
                    llm_client,
                )
            )
        results = []
        batch_size = 6
        for i in range(0, len(tasks), batch_size):
            batch = tasks[i : i + batch_size]
            results.extend(await asyncio.gather(*batch))
        return results

    validation_results = asyncio.run(run_all_validations())

    confirmed: List[Dict] = list(skip_validation)
    rejected: List[Dict] = []

    for finding, validation in validation_results:
        verdict = validation.get("verdict", "confirmed")
        confidence = float(validation.get("confidence", 0.5))
        reasoning = validation.get("reasoning", "")

        finding["validation"] = {
            "verdict": verdict,
            "confidence": confidence,
            "reasoning": reasoning,
        }

        if verdict == "rejected" and confidence >= 0.75:
            rejected.append(finding)
            console.print(
                f"  [dim red]✗ Rejected ({confidence:.0%}): "
                f"{finding.get('rule')} on "
                f"{str(finding.get('file', '')).split('/')[-1]} — "
                f"{str(reasoning)[:80]}[/dim red]"
            )

        elif verdict == "downgraded":
            old_severity = finding.get("severity")
            new_severity = validation.get("downgrade_to", "LOW")
            if new_severity not in ("MEDIUM", "LOW", "INFO"):
                new_severity = "LOW"
            finding["severity"] = new_severity
            finding["severity_downgraded_from"] = old_severity
            confirmed.append(finding)
            console.print(
                f"  [dim yellow]↓ Downgraded: "
                f"{finding.get('rule')} "
                f"{old_severity}→{new_severity}[/dim yellow]"
            )

        else:
            confirmed.append(finding)
            if verdict == "confirmed" and confidence >= 0.85:
                console.print(
                    f"  [dim green]✓ Confirmed ({confidence:.0%}): "
                    f"{finding.get('rule')} on "
                    f"{str(finding.get('file', '')).split('/')[-1]}[/dim green]"
                )

    n_down = sum(1 for f in confirmed if f.get("severity_downgraded_from"))
    console.print(
        f"\n  [bold]Validation complete:[/bold] "
        f"{len(confirmed)} confirmed, {len(rejected)} rejected, {n_down} downgraded"
    )

    return confirmed, rejected
